=== KissGergoBKUPJ9/BKUPJ9_XMLGyak/Féléves beadandó/1.feladat/XMLSchemaBKUPJ9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="idojarasallomas_adatok" type="idojarasallomasAdatokTipus">
    </xs:element>
    <xs:complexType name="idojarasallomasAdatokTipus">
        <xs:sequence>
            <xs:element name="szenzorállomás" type="szenzorállomásTípus" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="elosztóközpont" type="elosztóközpontTípus" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="előrejelzőállomás" type="előrejelzőállomásTípus" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="monitorozás" type="monitorozásTípus" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

        <xs:complexType name="szenzorállomásTípus">
            <xs:sequence>
                <xs:element name="szenzorID" type="xs:int"/>
                <xs:element name="szél" type="szélTípus"/>
                <xs:element name="adatok" type="adatokTípus"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="elosztóközpontTípus">
            <xs:sequence>
                <xs:element name="központID" type="xs:int"/>
                <xs:element name="elosztandóAdat" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="előrejelzőállomásTípus">
            <xs:sequence>
                <xs:element name="előrejelzőID" type="xs:int"/>
                <xs:element name="algoritmizáltAdat" type="algoritmizáltAdatTípus"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="monitorozásTípus">
            <xs:sequence>
                <xs:element name="monitorID" type="xs:int"/>
                <xs:element name="várhatóIdőjárás" type="xs:string"/>
                <xs:element name="aktuálisIdőjárás" type="xs:string"/>
                <xs:element name="idő" type="xs:int"/>
                <xs:element name="statisztika" type="statisztikaTípus"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="szélTípus">
            <xs:sequence>
                <xs:element name="szélirány" type="xs:string"/>
                <xs:element name="szélsebesség" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="adatokTípus">
            <xs:sequence>
                <xs:element name="páratartalom" type="xs:int"/>
                <xs:element name="hőmérséklet" type="xs:int"/>
                <xs:element name="légnyomás" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="algoritmizáltAdatTípus">
            <xs:sequence>
                <xs:element name="megbecsültIdőjárás" type="xs:string"/>
                <xs:element name="nyersadatok" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="statisztikaTípus">
            <xs:sequence>
                <xs:element name="elmúltIdőjárás" type="xs:string"/>
                <xs:element name="előrejelzésPontossága" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
</xs:schema>

=== KissGergoBKUPJ9/BKUPJ9_XMLGyak/XMLTaskBKUPJ9/2.feladat/DOMParseBKUPJ9/XMLBKUPJ9.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><idojarasallomas_adatok xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="XMLSchemaBKUPJ9.xsd">

    <szenzorállomások>
        <szenzorállomás központID="01" szenzorID="01">
            <szél>
                <szélirány>keleti</szélirány>
                <szélsebesség>34</szélsebesség>
            </szél>
            <adatok>
                <páratartalom>87</páratartalom>
                <hőmérséklet>22</hőmérséklet>
                <légnyomás>1011</légnyomás>
            </adatok>
        </szenzorállomás>

        <szenzorállomás központID="02" szenzorID="02">
            <szél>
                <szélirány>nyugati</szélirány>
                <szélsebesség>12</szélsebesség>
            </szél>
            <adatok>
                <páratartalom>67</páratartalom>
                <hőmérséklet>18</hőmérséklet>
                <légnyomás>1001</légnyomás>
            </adatok>
        </szenzorállomás>
    </szenzorállomások>

    <elosztóközpontok>
        <elosztóközpont előrejelzőID="01" központID="01" monitorID="01" szenzorID="01">
            <elosztandóAdat>szenzoradatok</elosztandóAdat>
        </elosztóközpont>

        <elosztóközpont előrejelzőID="02" központID="02" monitorID="02" szenzorID="02">
            <elosztandóAdat>algoritmizáltadat</elosztandóAdat>
        </elosztóközpont>
    </elosztóközpontok>

    <előrejelzőállomások>
        <előrejelzőállomás előrejelzőID="01" központID="01">
            <algoritmizáltAdat>
                <megbecsültIdőjárás>Napos, enyhén szeles, kellemesen meleg</megbecsültIdőjárás>
                <nyersadatok>Keleti, 34, 87, 22, 1011</nyersadatok>
            </algoritmizáltAdat>
        </előrejelzőállomás>

        <előrejelzőállomás előrejelzőID="02" központID="01">
            <algoritmizáltAdat>
                <megbecsültIdőjárás>Szeles, borús, hűvös</megbecsültIdőjárás>
                <nyersadatok>Nyugati, 12, 67, 18, 1001</nyersadatok>
            </algoritmizáltAdat>
        </előrejelzőállomás>
    </előrejelzőállomások>

    <monitorozások>
        <monitorozás központId="01" monitorID="01">
            <várhatóIdőjárás>Napos, enyhén szeles, kellemesen meleg</várhatóIdőjárás>
            <aktuálisIdőjárás>Meleg, száraz</aktuálisIdőjárás>
            <idő>12:20</idő>
            <statisztika>
                <elmúltIdőjárás>melegebb az átlagosnál</elmúltIdőjárás>
                <előrejelzésPontossága>pontos</előrejelzésPontossága>
            </statisztika>
        </monitorozás>

        <monitorozás központId="02" monitorID="02">
            <várhatóIdőjárás>Szeles, borús, hűvös</várhatóIdőjárás>
            <aktuálisIdőjárás>napos</aktuálisIdőjárás>
            <idő>14:10</idő>
            <statisztika>
                <elmúltIdőjárás>átlagosnál hűvösebb</elmúltIdőjárás>
                <előrejelzésPontossága>pontos</előrejelzésPontossága>
            </statisztika>
        <monitorozó>Béla</monitorozó><monitorozó>Béla</monitorozó><monitorozó>Béla</monitorozó><monitorozó>Béla</monitorozó><monitorozó>Béla</monitorozó></monitorozás>
    </monitorozások>

</idojarasallomas_adatok>

=== KissGergoBKUPJ9/BKUPJ9_XMLGyak/XMLTaskBKUPJ9/1.feladat/XMLFeladatBKUPJ9.xml
<?xml version="1.0" encoding="UTF-8"?>
<idojarasallomas_adatok xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="XMLSchemaBKUPJ9.xsd">

    <szenzorállomások>
        <szenzorállomás szenzorID="01" központID="01">
            <szél>
                <szélirány>keleti</szélirány>
                <szélsebesség>34</szélsebesség>
            </szél>
            <adatok>
                <páratartalom>87</páratartalom>
                <hőmérséklet>22</hőmérséklet>
                <légnyomás>1011</légnyomás>
            </adatok>
        </szenzorállomás>

        <szenzorállomás szenzorID="02" központID="02">
            <szél>
                <szélirány>nyugati</szélirány>
                <szélsebesség>12</szélsebesség>
            </szél>
            <adatok>
                <páratartalom>67</páratartalom>
                <hőmérséklet>18</hőmérséklet>
                <légnyomás>1001</légnyomás>
            </adatok>
        </szenzorállomás>
    </szenzorállomások>

    <elosztóközpontok>
        <elosztóközpont központID="01" szenzorID="01" előrejelzőID="01" monitorID="01">
            <elosztandóAdat>szenzoradatok</elosztandóAdat>
        </elosztóközpont>

        <elosztóközpont központID="02" szenzorID="02" előrejelzőID="02" monitorID="02">
            <elosztandóAdat>algoritmizáltadat</elosztandóAdat>
        </elosztóközpont>
    </elosztóközpontok>

    <előrejelzőállomások>
        <előrejelzőállomás előrejelzőID="01" központID="01">
            <algoritmizáltAdat>
                <megbecsültIdőjárás>Napos, enyhén szeles, kellemesen meleg</megbecsültIdőjárás>
                <nyersadatok>Keleti, 34, 87, 22, 1011</nyersadatok>
            </algoritmizáltAdat>
        </előrejelzőállomás>

        <előrejelzőállomás előrejelzőID="02" központID="01">
            <algoritmizáltAdat>
                <megbecsültIdőjárás>Szeles, borús, hűvös</megbecsültIdőjárás>
                <nyersadatok>Nyugati, 12, 67, 18, 1001</nyersadatok>
            </algoritmizáltAdat>
        </előrejelzőállomás>
    </előrejelzőállomások>

    <monitorozások>
        <monitorozás monitorID="01" központId="01">
            <várhatóIdőjárás>Napos, enyhén szeles, kellemesen meleg</várhatóIdőjárás>
            <aktuálisIdőjárás>Meleg, száraz</aktuálisIdőjárás>
            <idő>12:20</idő>
            <statisztika>
                <elmúltIdőjárás>melegebb az átlagosnál</elmúltIdőjárás>
                <előrejelzésPontossága>pontos</előrejelzésPontossága>
            </statisztika>
        </monitorozás>

        <monitorozás monitorID="02" központId="02">
            <várhatóIdőjárás>Szeles, borús, hűvös</várhatóIdőjárás>
            <aktuálisIdőjárás>Hűvös, esős</aktuálisIdőjárás>
            <idő>14:10</idő>
            <statisztika>
                <elmúltIdőjárás>átlagosnál hűvösebb</elmúltIdőjárás>
                <előrejelzésPontossága>pontos</előrejelzésPontossága>
            </statisztika>
        </monitorozás>
    </monitorozások>

</idojarasallomas_adatok>
